const GRAPH='https://graph.microsoft.com/v1.0';
const SCOPES=['User.Read','Mail.ReadBasic'];
let msalApp=null,account=null,allRows=[];
const $=id=>document.getElementById(id);

function config(){return{auth:{clientId:localStorage.getItem('followupClientId')||'',authority:'https://login.microsoftonline.com/common',redirectUri:'https://alaadika.github.io/outlook-followup/auth.html'},cache:{cacheLocation:'sessionStorage'}}}
function initAuth(){const id=localStorage.getItem('followupClientId');if(!id)return;msalApp=new msal.PublicClientApplication(config());const accts=msalApp.getAllAccounts();if(accts.length){account=accts[0];$('authState').textContent=account.username;$('setup').style.display='none'}}
async function login(){if(!localStorage.getItem('followupClientId'))return alert('Enter and save your Microsoft Application (client) ID first.');initAuth();try{const r=await msalApp.loginPopup({scopes:SCOPES});account=r.account;$('authState').textContent=account.username;$('setup').style.display='none'}catch(e){showError(e)}}
async function token(){if(!msalApp||!account)throw new Error('Please sign in first.');try{return(await msalApp.acquireTokenSilent({account,scopes:SCOPES})).accessToken}catch{return(await msalApp.acquireTokenPopup({account,scopes:SCOPES})).accessToken}}
async function graph(path){const t=await token();const r=await fetch(GRAPH+path,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error(`Microsoft Graph ${r.status}: ${await r.text()}`);return r.json()}
async function paged(path,max=1200){let out=[];let url=GRAPH+path;const t=await token();while(url&&out.length<max){const r=await fetch(url,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error(`Microsoft Graph ${r.status}: ${await r.text()}`);const j=await r.json();out.push(...(j.value||[]));url=j['@odata.nextLink']||null}return out.slice(0,max)}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function addresses(m){return(m.toRecipients||[]).map(x=>x.emailAddress?.address||x.emailAddress?.name||'').filter(Boolean)}
function replySender(m){return m.from?.emailAddress?.address||m.sender?.emailAddress?.address||''}
async function scan(){try{$('scan').disabled=true;$('status').textContent='Scanning Microsoft 365…';const days=+$('days').value;const since=new Date(Date.now()-days*86400000).toISOString();const select='id,subject,sentDateTime,receivedDateTime,toRecipients,from,sender,importance,flag,conversationId,webLink';const sent=await paged(`/me/mailFolders/sentitems/messages?$select=${select}&$filter=sentDateTime ge ${encodeURIComponent(since)}&$orderby=sentDateTime desc&$top=100`);const inbox=await paged(`/me/mailFolders/inbox/messages?$select=${select}&$filter=receivedDateTime ge ${encodeURIComponent(since)}&$orderby=receivedDateTime desc&$top=100`);const byConv=new Map();for(const m of inbox){if(!m.conversationId)continue;if(!byConv.has(m.conversationId))byConv.set(m.conversationId,[]);byConv.get(m.conversationId).push(m)}allRows=sent.map(s=>{const replies=(byConv.get(s.conversationId)||[]).filter(r=>new Date(r.receivedDateTime)>new Date(s.sentDateTime)).sort((a,b)=>new Date(a.receivedDateTime)-new Date(b.receivedDateTime));const reply=replies[0]||null;return{sent:s,reply,replied:!!reply,high:s.importance==='high',flagged:s.flag?.flagStatus==='flagged'||s.flag?.flagStatus==='complete',to:addresses(s).join('; '),responder:reply?replySender(reply):''}});render();$('status').textContent=`Scan complete: ${allRows.length} sent messages checked.`}catch(e){showError(e)}finally{$('scan').disabled=false}}
function filtered(){const q=$('search').value.trim().toLowerCase(),show=$('show').value;return allRows.filter(r=>{if($('needs').checked&&!r.replied)return match(r);if($('needs').checked&&r.replied)return false;if($('high').checked&&!r.high)return false;if($('flagged').checked&&!r.flagged)return false;if(show==='needs'&&r.replied)return false;if(show==='replied'&&!r.replied)return false;return match(r);function match(x){if($('high').checked&&!x.high)return false;if($('flagged').checked&&!x.flagged)return false;if(show==='replied'&&!x.replied)return false;if(show==='needs'&&x.replied)return false;return !q||[x.sent.subject,x.to,x.responder].some(v=>(v||'').toLowerCase().includes(q))}})}
function render(){const rows=filtered();$('rows').innerHTML=rows.map(r=>`<tr><td>${esc(new Date(r.sent.sentDateTime).toLocaleString())}</td><td>${esc(r.sent.subject||'(no subject)')}</td><td>${esc(r.to)}</td><td class="${r.high?'high':''}">${r.high?'High':'Normal'}</td><td class="flag">${r.flagged?'⚑':''}</td><td class="${r.replied?'yes':'no'}">${r.replied?'YES':'NO'}</td><td>${esc(r.responder||'—')}</td><td class="actions">${r.sent.webLink?`<a href="${esc(r.sent.webLink)}" target="_blank" rel="noopener">Open Sent</a>`:''}${r.reply?.webLink?`<a href="${esc(r.reply.webLink)}" target="_blank" rel="noopener">Open Reply</a>`:''}</td></tr>`).join('');$('counts').textContent=`${rows.length} shown · ${allRows.filter(r=>!r.replied).length} need follow-up · ${allRows.filter(r=>r.replied).length} replied`}
function csvCell(v){v=String(v??'');if(/^[=+\-@]/.test(v))v="'"+v;return '"'+v.replace(/"/g,'""')+'"'}
function exportCsv(){const rows=filtered(),data=[['Sent','Subject','To','High Importance','Flagged','Replied','Replied By'],...rows.map(r=>[r.sent.sentDateTime,r.sent.subject,r.to,r.high,r.flagged,r.replied,r.responder])];const blob=new Blob([data.map(x=>x.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='outlook-followup.csv';a.click();URL.revokeObjectURL(a.href)}
function showError(e){console.error(e);$('status').textContent=e.message||String(e);alert(e.message||String(e))}
$('saveClient').onclick=()=>{const v=$('clientId').value.trim();if(!v)return alert('Enter the Application (client) ID.');localStorage.setItem('followupClientId',v);initAuth();alert('Client ID saved locally in this browser.')};$('signIn').onclick=login;$('scan').onclick=scan;$('export').onclick=exportCsv;['needs','high','flagged','show'].forEach(id=>$(id).onchange=render);$('search').oninput=render;$('clientId').value=localStorage.getItem('followupClientId')||'';
if(window.Office)Office.onReady(()=>initAuth());else initAuth();
